// <auto-generated />
using System;
using FundingApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FundingApplication.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231226134303_NewDate")]
    partial class NewDate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FundingApplication.Models.MonthSalary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Salary")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("SalaryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("dateOfTransaction")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("month")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SalaryId");

                    b.ToTable("monthSalaries");
                });

            modelBuilder.Entity("FundingApplication.Models.Salary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<double>("total")
                        .HasColumnType("double precision");

                    b.Property<int>("year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("salaries");
                });

            modelBuilder.Entity("FundingApplication.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("age")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("FundingApplication.Models.MonthSalary", b =>
                {
                    b.HasOne("FundingApplication.Models.Salary", null)
                        .WithMany("monthSalaries")
                        .HasForeignKey("SalaryId");
                });

            modelBuilder.Entity("FundingApplication.Models.Salary", b =>
                {
                    b.HasOne("FundingApplication.Models.User", null)
                        .WithMany("salaries")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("FundingApplication.Models.Salary", b =>
                {
                    b.Navigation("monthSalaries");
                });

            modelBuilder.Entity("FundingApplication.Models.User", b =>
                {
                    b.Navigation("salaries");
                });
#pragma warning restore 612, 618
        }
    }
}
